apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      serviceAccountName: app
      containers:
      - name: test
        image: postgres:alpine
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PGHOST
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PGPORT
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PGUSER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PGPASSWORD
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PGDATABASE
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
        env:
        - name: INSTANCES
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: CLOUDSQL_PROXY_INSTANCES
        securityContext:
          runAsNonRoot: true