apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.15.2