apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  targetNamespace: external-dns
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: external-dns
    version: 3.2.3
  values:
    provider: google
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: "external-dns-gke-sa@taurus-279813.iam.gserviceaccount.com"